version: '3'

services:
    memcached:
        image: memcached:latest
        ports:
            - "11211:11211"
        environment:
          - MEMCACHED_USERNAME=root
          - MEMCACHED_PASSWORD=asdasd